<?php

namespace NickDeKruijk\LeapTemplate\Commands;

use Illuminate\Console\Command;
use Illuminate\Console\ConfirmableTrait;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;

use function Laravel\Prompts\confirm;

/**
 * Remove a content type generated by leap:content — the counterpart nobody had, which
 * made a typo in `leap:template --models=…` something you undid by hand across five
 * files, the registry, a table and the page that lists it.
 *
 * Files and the registry entry go. The table, its migration record, its tag links and
 * its overview page are asked about separately and default to staying: a mistyped name
 * and a type you have been filling for a month look identical from here.
 */
class ContentDeleteCommand extends Command
{
    use ConfirmableTrait;

    protected $signature = 'leap:content-delete {name : The model name, e.g. NewsProject}
        {--plural= : Override the plural used for the table and registry key}
        {--drop-table : Drop the table, its overview page and its tag links without asking}
        {--force : Skip the confirmation}';

    protected $description = 'Remove a generated content type: its files, its registry entry, optionally its table';

    /**
     * The template's own models. Deleting one of these takes the site with it.
     *
     * @var array<int, string>
     */
    protected array $reserved = ['Page', 'Tag', 'User'];

    public function handle(): int
    {
        if (! $this->confirmToProceed()) {
            return 1;
        }

        $name = Str::studly($this->argument('name'));

        if (in_array($name, $this->reserved, true)) {
            $this->error("[{$name}] belongs to the template itself and cannot be deleted.");

            return 1;
        }

        $plural = $this->option('plural') ?: Str::plural($name);
        $table = Str::snake($plural);
        $key = Str::kebab($plural);

        // Whether this type actually owns the table and registry key its name derives to.
        // It does not when another model got there first: Str::plural('Events') is
        // 'Events', so deleting a stray `Events` type would otherwise take the real
        // Event's table, page and registration with it.
        $owner = $this->registeredClass($key);
        $owned = $owner === null || ltrim($owner, '\\') === "App\\Models\\{$name}";

        $files = $this->filesFor($name, $table, $owned);

        if ($files === [] && ! ($owned && $owner !== null)) {
            $this->components->info("Nothing to remove — no files or registry entry for [{$name}].");

            return 0;
        }

        if (! $owned) {
            $this->components->warn("leap.content['{$key}'] belongs to {$owner}, not to {$name} — leaving the registry, the '{$table}' table and its migration alone.");
        }

        if (! $this->confirmRemoval($name, $files, $owned && $owner !== null, $key)) {
            $this->components->info('Nothing removed.');

            return 0;
        }

        foreach ($files as $path) {
            unlink(base_path($path));
            $this->components->twoColumnDetail($path, '<fg=red>deleted</>');
        }

        if ($owned) {
            $this->removeFromConfig($key);
            $this->handleTable($name, $table, $key);
        }

        $this->components->info("Removed content type [{$name}].");

        return 0;
    }

    /**
     * The generated files that still exist. The migration is only one of them when this
     * type owns the table — a shared table's migration belongs to whoever came first.
     *
     * @return array<int, string>
     */
    protected function filesFor(string $name, string $table, bool $owned): array
    {
        $paths = [
            "app/Models/{$name}.php",
            "app/Leap/{$name}.php",
            "database/factories/{$name}Factory.php",
            "database/seeders/{$name}Seeder.php",
        ];

        if ($owned && ($migration = $this->migrationPath($table)) !== null) {
            $paths[] = $migration;
        }

        return array_values(array_filter($paths, fn (string $path): bool => file_exists(base_path($path))));
    }

    /**
     * The type's create-table migration, if it is still around. Matched by table name
     * rather than by timestamp, the same way leap:content finds it to reuse.
     */
    protected function migrationPath(string $table): ?string
    {
        $found = glob(base_path("database/migrations/*_create_{$table}_table.php"));

        return $found ? 'database/migrations/'.basename($found[0]) : null;
    }

    /**
     * The class config('leap.content') has under this key, read from the file rather than
     * from config() so it reflects what is on disk after an edit in the same run.
     */
    protected function registeredClass(string $key): ?string
    {
        $path = base_path('config/leap.php');

        if (! file_exists($path)) {
            return null;
        }

        $contents = (string) file_get_contents($path);

        if (! preg_match(ContentCommand::CONTENT_ARRAY, $contents, $array)) {
            return null;
        }

        if (! preg_match("/^\s*'".preg_quote($key, '/')."'\s*=>\s*([^,\n]+?)::class/m", $array[2], $entry)) {
            return null;
        }

        $class = trim($entry[1]);

        // Written as a short name, so an import decides what it means. The generator only
        // ever registers models, and the template keeps them in one namespace.
        return str_contains($class, '\\') ? $class : "App\\Models\\{$class}";
    }

    /**
     * @param  array<int, string>  $files
     */
    protected function confirmRemoval(string $name, array $files, bool $registered, string $key): bool
    {
        $this->components->info("About to remove content type [{$name}]:");

        foreach ($files as $path) {
            $this->components->twoColumnDetail($path, '<fg=yellow>delete</>');
        }

        if ($registered) {
            $this->components->twoColumnDetail("config/leap.php → leap.content['{$key}']", '<fg=yellow>unregister</>');
        }

        if ($this->option('force') || ! $this->input->isInteractive()) {
            return true;
        }

        return confirm('Remove these?', default: false);
    }

    /**
     * The table and everything hanging off it. Dropped only when asked for: --drop-table
     * answers yes up front, otherwise the question defaults to no, so a reflex Enter — or
     * a run with no tty — keeps the data.
     */
    protected function handleTable(string $name, string $table, string $key): void
    {
        if (! Schema::hasTable($table)) {
            return;
        }

        if (! $this->option('drop-table')) {
            $rows = DB::table($table)->count();

            $wanted = $this->input->isInteractive() && confirm(
                "'{$table}' has {$rows} rows, plus its overview page and tag links. Drop the table as well?",
                default: false,
            );

            if (! $wanted) {
                $this->components->warn("Kept the '{$table}' table. Remove it later with: php artisan leap:content-delete {$name} --drop-table");

                return;
            }
        }

        $this->deleteTagLinks($name);
        $this->deleteOverviewPage($key);

        Schema::drop($table);
        $this->components->twoColumnDetail("{$table} table", '<fg=red>dropped</>');

        // The migration file is gone, so its row would otherwise keep a phantom entry that
        // makes migrate:status lie about what has run.
        if (Schema::hasTable('migrations')) {
            DB::table('migrations')->where('migration', 'like', "%_create_{$table}_table")->delete();
        }
    }

    /**
     * Tag links live in a polymorphic pivot, so dropping the table leaves them behind
     * pointing at rows that no longer exist.
     */
    protected function deleteTagLinks(string $name): void
    {
        if (! Schema::hasTable('taggables')) {
            return;
        }

        $deleted = DB::table('taggables')->where('taggable_type', "App\\Models\\{$name}")->delete();

        if ($deleted) {
            $this->components->twoColumnDetail("{$deleted} taggables rows", '<fg=red>deleted</>');
        }
    }

    /**
     * The overview page that lists the type. Without its content it renders an empty
     * list, so it goes along with the table — a page called Projects with no projects on
     * it is worse than no page.
     */
    protected function deleteOverviewPage(string $key): void
    {
        $model = 'App\Models\Page';

        if (! class_exists($model) || ! Schema::hasTable('pages')) {
            return;
        }

        foreach ($model::all() as $page) {
            $lists = collect($page->sections ?? [])
                ->contains(fn ($section): bool => ($section['_name'] ?? null) === $key);

            if ($lists) {
                $page->forceDelete();
                $this->components->twoColumnDetail("page [{$page->id}] listing '{$key}'", '<fg=red>deleted</>');
            }
        }
    }

    /**
     * Drop the type's line from config('leap.content'), leaving the rest of the array —
     * and the order of what remains — untouched.
     */
    protected function removeFromConfig(string $key): void
    {
        $path = base_path('config/leap.php');

        if (! file_exists($path)) {
            return;
        }

        $contents = (string) file_get_contents($path);

        $patched = preg_replace_callback(
            ContentCommand::CONTENT_ARRAY,
            function (array $m) use ($key): string {
                $body = preg_replace(
                    "/^[ \t]*'".preg_quote($key, '/')."'\s*=>.*\R/m",
                    '',
                    $m[2]
                );

                return "{$m[1]}'content' => [".rtrim((string) $body, "\n")."\n{$m[1]}]";
            },
            $contents,
            1,
            $count
        );

        if ($count && $patched !== $contents) {
            file_put_contents($path, $patched);
            $this->components->twoColumnDetail("config/leap.php → leap.content['{$key}']", '<fg=red>unregistered</>');
        }
    }
}
